import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { AIResponse, MonthPlan, Meal } from "../types";

export const generatePDF = (plan: AIResponse) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 15;
    const contentWidth = pageWidth - (margin * 2);

    const userName = plan.userStats.name || "Valued Member";
    const userEmail = plan.userStats.email || "";
    const unit = plan.userStats.unit || 'metric';
    const isLeftoverStrategy = plan.userStats.mealStrategy === 'leftovers';
    const includeSnacks = plan.userStats.includeSnacks;

    // --- HELPER: CENTERED TEXT ---
    const centerText = (text: string, y: number, size: number, font: string = "helvetica", style: string = "normal") => {
        doc.setFont(font, style);
        doc.setFontSize(size);
        doc.text(text, pageWidth / 2, y, { align: "center" });
    };

    // --- HELPER: COLORED BOX ---
    const drawSectionHeader = (text: string, y: number, color: [number, number, number]) => {
        doc.setFillColor(...color);
        doc.rect(margin, y, contentWidth, 10, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.text(text.toUpperCase(), margin + 5, y + 7);
        doc.setTextColor(30, 41, 59); // Reset
        return y + 15;
    };

    // --- PAGE 1: THE MANIFESTO (COVER) ---
    doc.setFillColor(16, 185, 129); // Emerald 500
    doc.rect(0, 0, pageWidth, pageHeight, "F");

    doc.setTextColor(255, 255, 255);
    centerText("DIETLY PLANS", 40, 16, "helvetica", "bold");
    centerText("12-WEEK TRANSFORMATION", 100, 32, "helvetica", "bold");
    centerText("OFFICIAL ROADMAP", 115, 14);

    // White Box for User Details
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(margin, 140, contentWidth, 100, 4, 4, "F");

    doc.setTextColor(30, 41, 59);
    centerText(`PREPARED FOR: ${userName.toUpperCase()}`, 160, 14, "helvetica", "bold");
    if (userEmail) {
        centerText(userEmail.toLowerCase(), 168, 10, "helvetica", "normal");
    }
    centerText(`GOAL: ${plan.userStats.goal.toUpperCase()}`, 178, 11, "helvetica", "bold");

    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 20, 185, pageWidth - (margin + 20), 185);

    // Stats Grid on Cover (Fixed Imperial Conversion)
    doc.setFontSize(10);

    const displayWeight = unit === 'metric'
        ? `${plan.userStats.weight} kg`
        : `${Math.round(plan.userStats.weight * 2.20462)} lbs`;

    let displayHeight = `${plan.userStats.height} cm`;
    if (unit === 'imperial') {
        const totalInches = plan.userStats.height / 2.54;
        const ft = Math.floor(totalInches / 12);
        const inch = Math.round(totalInches % 12);
        displayHeight = `${ft}' ${inch}"`;
    }

    doc.text(`Starting Weight: ${displayWeight}`, margin + 20, 200);
    doc.text(`Height: ${displayHeight}`, pageWidth - 60, 200);
    doc.text(`Diet Type: ${plan.userStats.dietType}`, margin + 20, 210);
    doc.text(`Cuisine: ${plan.userStats.cuisine}`, pageWidth - 60, 210);
    doc.text(`Strategy: ${plan.userStats.mealStrategy === 'leftovers' ? 'Cook Dinner -> Lunch' : 'Fresh Meals'}`, margin + 20, 220);
    doc.text(`Region: ${plan.userStats.region || 'Global'}`, pageWidth - 60, 220);

    centerText("Generated by Dietly AI", 235, 9, "helvetica", "italic");

    // --- PAGE 2: EXECUTIVE SUMMARY (SAFETY & STRATEGY) ---
    doc.addPage();
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    doc.setTextColor(30, 41, 59);

    let cursorY = 20;
    centerText("EXECUTIVE SUMMARY", cursorY, 20, "helvetica", "bold");
    cursorY += 15;

    // 1. Clinical Analysis
    cursorY = drawSectionHeader("Clinical & Safety Analysis", cursorY, [4, 120, 87]); // Dark Green

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const safetyText = `${plan.safetyVerification}\n\nMEDICATIONS: ${plan.medicationAnalysis || "No interaction warnings triggered."}\n\nALLERGIES: ${plan.userStats.allergies || "None reported."}`;
    const splitSafety = doc.splitTextToSize(safetyText, contentWidth - 10);
    doc.text(splitSafety, margin + 5, cursorY);
    cursorY += (splitSafety.length * 5) + 10;

    // 2. Metabolic Profile WITH UNIT CONVERSION
    cursorY = drawSectionHeader("Metabolic Profile", cursorY, [14, 165, 233]); // Sky Blue
    const bmrText = `Basal Metabolic Rate (BMR): ${Math.round(plan.userStats.bmr)} kcal/day`;
    const tdeeText = `Total Energy Expenditure (TDEE): ${Math.round(plan.userStats.tdee)} kcal/day`;
    const bmiText = `Current BMI: ${plan.userStats.bmi}`;

    // UNIT AWARE WATER LOGIC
    let waterStr = "";
    if (unit === 'imperial') {
        const oz = Math.round(plan.userStats.waterTargetLitres * 33.814);
        waterStr = `${oz} fl oz/day (~${plan.userStats.waterTargetLitres} Liters)`;
    } else {
        waterStr = `${plan.userStats.waterTargetLitres} Liters/day`;
    }

    const waterText = `Hydration Target: ${waterStr} ${plan.userStats.needsElectrolytes ? "(High Volume - Electrolytes Recommended)" : ""}`;

    doc.text(`• ${bmrText}`, margin + 5, cursorY);
    doc.text(`• ${tdeeText}`, margin + 5, cursorY + 6);
    doc.text(`• ${bmiText}`, margin + 5, cursorY + 12);
    doc.text(`• ${waterText}`, margin + 5, cursorY + 18);
    cursorY += 30;

    // 3. Strategic Adjustments
    cursorY = drawSectionHeader("Strategic Intelligence", cursorY, [245, 158, 11]); // Amber
    const climateTxt = plan.climateAnalysis ? `Climate: ${plan.climateAnalysis.advice}` : "";
    const budgetTxt = plan.budgetStrategy ? `Budget: ${plan.budgetStrategy}` : "";
    const pantryTxt = plan.pantryTips ? `Pantry: ${plan.pantryTips}` : "";

    const strategyBlob = [climateTxt, budgetTxt, pantryTxt].filter(Boolean).join("\n\n");
    const splitStrat = doc.splitTextToSize(strategyBlob, contentWidth - 10);
    doc.text(splitStrat, margin + 5, cursorY);


    // --- HELPER: RENDER MONTH ---
    const renderMonth = (monthData: MonthPlan, monthNum: number) => {
        // 1. MONTH COVER
        doc.addPage();
        doc.setFillColor(30, 41, 59); // Slate 800
        doc.rect(0, 0, pageWidth, pageHeight, "F");

        doc.setTextColor(255, 255, 255);
        centerText(`PHASE ${monthNum}`, 120, 40, "helvetica", "bold");

        doc.setTextColor(16, 185, 129); // Emerald
        centerText(monthData.phaseName.toUpperCase(), 140, 20, "helvetica", "bold");

        doc.setTextColor(200, 200, 200);
        centerText(`Daily Calorie Target: ${monthData.targetCalories} kcal`, 155, 14);

        // 2. WEEKLY SCHEDULES (Tables)
        for (let i = 0; i < 4; i++) {
            const weekNum = i + 1;
            doc.addPage();
            doc.setFillColor(255, 255, 255);
            doc.rect(0, 0, pageWidth, pageHeight, "F"); // White BG

            doc.setTextColor(15, 23, 42);
            doc.setFontSize(18);
            doc.setFont("helvetica", "bold");
            doc.text(`Month ${monthNum} / Week ${weekNum}`, margin, 25);

            // Table Data
            const startDay = i * 7;
            const weekMeals = monthData.dailyPlan.slice(startDay, startDay + 7);

            // DYNAMIC HEADERS based on snack preference
            const headers = includeSnacks
                ? [['Day', 'Breakfast', 'Lunch', 'Dinner', 'Snack']]
                : [['Day', 'Breakfast', 'Lunch', 'Dinner']];

            const tableBody = weekMeals.map(d => {
                let lunchText = d.meals.lunch.name;
                // PDF Visual Logic for Leftovers
                if (isLeftoverStrategy && d.day > 1) {
                    lunchText = `(REHEAT) ${lunchText}`;
                }

                const row = [
                    `Day ${d.day}`,
                    d.meals.breakfast.name,
                    lunchText,
                    d.meals.dinner.name
                ];

                if (includeSnacks) {
                    row.push(d.meals.snack ? d.meals.snack.name : '-');
                }

                return row;
            });

            autoTable(doc, {
                startY: 35,
                head: headers,
                body: tableBody,
                theme: 'grid',
                headStyles: { fillColor: [16, 185, 129] },
                styles: { fontSize: 8, cellPadding: 3 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 15 } }
            });

            // Weekly Shopping List
            let finalY = (doc as any).lastAutoTable.finalY + 15;
            doc.setFontSize(14);
            doc.text(`Shopping List - Week ${weekNum}`, margin, finalY);
            finalY += 8;

            const groceryKey = `week${weekNum}` as keyof typeof monthData.groceries;
            const groceries = monthData.groceries[groceryKey] || [];

            doc.setFontSize(9);
            doc.setFont("helvetica", "normal");

            if (groceries.length > 0) {
                groceries.forEach(cat => {
                    if (finalY > pageHeight - 20) { doc.addPage(); finalY = 20; }

                    doc.setFont("helvetica", "bold");
                    doc.text(cat.category.toUpperCase(), margin, finalY);
                    finalY += 4;

                    doc.setFont("helvetica", "normal");
                    const items = cat.items.join(", ");
                    const splitItems = doc.splitTextToSize(items, contentWidth);
                    doc.text(splitItems, margin, finalY);
                    finalY += (splitItems.length * 4) + 4;
                });
            } else {
                doc.text("Use pantry staples or refer to previous week.", margin, finalY);
            }
        }

        // 3. THE RECIPE BOOK (Unique Days 1-7)
        // We only print the first 7 days as the template repeats
        doc.addPage();
        doc.setFillColor(240, 253, 244); // Light Green Page
        doc.rect(0, 0, pageWidth, pageHeight, "F");

        doc.setTextColor(4, 120, 87);
        centerText(`THE COOKBOOK - MONTH ${monthNum}`, pageHeight / 2, 24, "helvetica", "bold");
        centerText("Detailed recipes for your weekly rotation", (pageHeight / 2) + 15, 12);

        const uniqueDays = monthData.dailyPlan.slice(0, 7);

        uniqueDays.forEach((day, idx) => {
            doc.addPage();
            doc.setFillColor(255, 255, 255);
            doc.rect(0, 0, pageWidth, pageHeight, "F");

            let y = 20;

            // Header
            doc.setFontSize(20);
            doc.setTextColor(30, 41, 59);
            doc.setFont("helvetica", "bold");
            doc.text(`Day ${idx + 1} Template`, margin, y);

            // Macro Summary
            doc.setFontSize(10);
            doc.setTextColor(100, 116, 139);
            doc.text(`Calories: ${day.dailyMacros.calories} | P: ${day.dailyMacros.protein}g | C: ${day.dailyMacros.carbs}g | F: ${day.dailyMacros.fats}g`, margin, y + 7);

            doc.setDrawColor(226, 232, 240);
            doc.line(margin, y + 12, pageWidth - margin, y + 12);
            y += 20;

            const renderRecipeBlock = (title: string, meal: Meal, isLeftoverSkip: boolean = false, prepNote: string = "") => {
                if (y > pageHeight - 60) { doc.addPage(); y = 20; }

                // Title Box
                doc.setFillColor(241, 245, 249); // Slate 100
                doc.rect(margin, y, contentWidth, 8, "F");
                doc.setFontSize(11);
                doc.setTextColor(15, 23, 42);
                doc.setFont("helvetica", "bold");
                doc.text(`${title.toUpperCase()}: ${meal.name}`, margin + 3, y + 5.5);
                y += 14;

                if (isLeftoverSkip) {
                    doc.setFontSize(10);
                    doc.setFont("helvetica", "italic");
                    doc.setTextColor(100, 116, 139);
                    doc.text("LEFTOVERS: Eat the portion saved from yesterday's dinner.", margin + 5, y);
                    y += 10;
                    return;
                }

                // Meta
                doc.setFontSize(9);
                doc.setFont("helvetica", "bold");
                doc.setTextColor(16, 185, 129); // Primary
                doc.text(`${meal.calories} kcal`, margin + 5, y);
                doc.setTextColor(30, 41, 59); // Dark
                doc.setFont("helvetica", "normal");

                // Ingredients
                y += 5;
                doc.setFont("helvetica", "bold");
                doc.text("Ingredients:", margin + 5, y);
                y += 5;
                doc.setFont("helvetica", "normal");
                const ingText = meal.ingredients.join(", ");
                const splitIng = doc.splitTextToSize(ingText, contentWidth - 10);
                doc.text(splitIng, margin + 5, y);
                y += (splitIng.length * 4) + 4;

                // Instructions
                doc.setFont("helvetica", "bold");
                doc.text("Instructions:", margin + 5, y);
                y += 5;
                doc.setFont("helvetica", "normal");

                meal.instructions.forEach((inst, i) => {
                    const step = `${i + 1}. ${inst}`;
                    const splitStep = doc.splitTextToSize(step, contentWidth - 10);

                    // Page break check within instructions
                    if (y + (splitStep.length * 4) > pageHeight - 10) {
                        doc.addPage();
                        y = 20;
                    }

                    doc.text(splitStep, margin + 5, y);
                    y += (splitStep.length * 4) + 2;
                });

                // Prep Note (e.g. for Dinner)
                if (prepNote) {
                    y += 2;
                    doc.setFont("helvetica", "bolditalic");
                    doc.setTextColor(249, 115, 22); // Orange
                    doc.text(prepNote, margin + 5, y);
                    doc.setTextColor(30, 41, 59); // Reset
                    y += 6;
                }

                y += 6; // Spacer
            };

            // Render Meals
            renderRecipeBlock("Breakfast", day.meals.breakfast);

            // Lunch Logic
            if (isLeftoverStrategy) {
                renderRecipeBlock("Lunch (Fresh Option)", day.meals.lunch, false, "NOTE: If following 'Cook Once' strategy, skip this and eat last night's dinner.");
            } else {
                renderRecipeBlock("Lunch", day.meals.lunch);
            }

            const dinnerPrepNote = isLeftoverStrategy ? "MEAL PREP: Cook double portion to save for tomorrow's lunch." : "";
            renderRecipeBlock("Dinner", day.meals.dinner, false, dinnerPrepNote);

            if (includeSnacks && day.meals.snack) {
                renderRecipeBlock("Snack", day.meals.snack);
            }
        });
    };

    // Render All Months
    renderMonth(plan.roadmap.month1, 1);
    renderMonth(plan.roadmap.month2, 2);
    renderMonth(plan.roadmap.month3, 3);

    // --- LAST PAGE: DISCLAIMER ---
    doc.addPage();
    centerText("DISCLAIMER", 100, 16, "helvetica", "bold");
    const disclaimer = "This meal plan is generated by Artificial Intelligence based on the data provided. It is not medical advice. Consult a healthcare professional before making drastic changes to your diet, especially if you have pre-existing conditions or are taking medication.\n\nDietlyPlans assumes no liability for adverse reactions or health complications.";
    const splitDisc = doc.splitTextToSize(disclaimer, contentWidth - 40);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(splitDisc, margin + 20, 120);

    doc.save(`${userName.replace(/\s+/g, '_')}_Transformation_Plan.pdf`);
};
