import React, { useState } from 'react';
import { ArrowLeft, Shield, FileText, Lock, AlertTriangle, CreditCard } from 'lucide-react';

interface LegalProps {
    onBack: () => void;
}

type Section = 'terms' | 'privacy' | 'refund' | 'medical';

export const Legal: React.FC<LegalProps> = ({ onBack }) => {
    const [activeSection, setActiveSection] = useState<Section>('medical');

    const navItems: { id: Section; label: string; icon: any }[] = [
        { id: 'medical', label: 'Medical Disclaimer', icon: AlertTriangle },
        { id: 'terms', label: 'Terms of Service', icon: FileText },
        { id: 'privacy', label: 'Privacy Policy', icon: Lock },
        { id: 'refund', label: 'Refund Policy', icon: CreditCard },
    ];

    return (
        <div className="fixed inset-0 z-[100] bg-white overflow-hidden flex flex-col animate-in slide-in-from-bottom-10 duration-300">
            {/* Header */}
            <div className="shrink-0 p-4 border-b border-slate-100 flex items-center justify-between bg-white z-20">
                <button
                    onClick={onBack}
                    className="flex items-center gap-2 text-slate-500 hover:text-dark font-bold transition-colors"
                >
                    <ArrowLeft className="w-5 h-5" />
                    Back to App
                </button>
                <div className="flex items-center gap-2 text-primary font-bold">
                    <Shield className="w-5 h-5" />
                    <span className="hidden sm:inline">Legal Center</span>
                </div>
            </div>

            <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
                {/* Sidebar Nav */}
                <div className="w-full md:w-64 bg-slate-50 border-r border-slate-100 shrink-0 overflow-x-auto md:overflow-y-auto flex md:flex-col gap-1 p-2 md:p-4">
                    {navItems.map((item) => (
                        <button
                            key={item.id}
                            onClick={() => setActiveSection(item.id)}
                            className={`flex items-center gap-3 p-3 rounded-xl font-bold text-sm transition-all whitespace-nowrap md:whitespace-normal ${activeSection === item.id
                                    ? 'bg-white text-primary shadow-sm ring-1 ring-slate-100'
                                    : 'text-slate-500 hover:bg-white/50 hover:text-slate-700'
                                }`}
                        >
                            <item.icon className={`w-4 h-4 ${activeSection === item.id ? 'text-primary' : 'text-slate-400'}`} />
                            {item.label}
                        </button>
                    ))}
                </div>

                {/* Content Area */}
                <div className="flex-1 overflow-y-auto p-6 md:p-12 scroll-smooth">
                    <div className="max-w-3xl mx-auto space-y-12 pb-20">

                        {/* MEDICAL DISCLAIMER */}
                        {activeSection === 'medical' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                                <div className="p-6 bg-amber-50 rounded-2xl border border-amber-100 text-amber-900">
                                    <h1 className="text-3xl font-black mb-6 flex items-center gap-3">
                                        <AlertTriangle className="w-8 h-8 text-amber-600" />
                                        Medical Disclaimer
                                    </h1>
                                    <p className="font-bold text-lg mb-4">
                                        DietlyPlans is NOT a medical device and does NOT provide medical advice.
                                    </p>
                                    <ul className="space-y-3 list-disc pl-5">
                                        <li>The content generated by this AI is for informational and educational purposes only.</li>
                                        <li>It is NOT intended to diagnose, treat, cure, or prevent any disease.</li>
                                        <li>You should strictly consult with a qualified healthcare professional before making any changes to your diet, exercise, or medication regimen.</li>
                                        <li>If you have a medical condition (e.g., Diabetes, Renal Disease, Eating Disorders), you must verify all AI suggestions with your specialist.</li>
                                        <li>In case of a medical emergency, call emergency services immediately.</li>
                                    </ul>
                                </div>
                            </div>
                        )}

                        {/* TERMS OF SERVICE */}
                        {activeSection === 'terms' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                                <h1 className="text-3xl font-black text-dark">Terms of Service</h1>
                                <p className="text-slate-500 text-sm">Last Updated: January 2026</p>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">1. Acceptance of Terms</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        By accessing or using DietlyPlans, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
                                    </p>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">2. AI Deployment & Limitations</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        You acknowledge that the services provided are generated by Artificial Intelligence. While we strive for accuracy, AI can hallucinate or provide incorrect information. You agree to use discretion and verify information.
                                    </p>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">3. User Conduct</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        You agree not to use the service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts. You will not input malicious data or attempt to reverse engineer the application.
                                    </p>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">4. Limitation of Liability</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        In no event shall DietlyPlans, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                                    </p>
                                </section>
                            </div>
                        )}

                        {/* PRIVACY POLICY */}
                        {activeSection === 'privacy' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                                <h1 className="text-3xl font-black text-dark">Privacy Policy</h1>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">1. Data Collection</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        We collect information you provide directly to us when using the meal planner wizard, including:
                                    </p>
                                    <ul className="list-disc pl-5 text-slate-600 space-y-1">
                                        <li>Basic biometric data (Age, Height, Weight, Gender) - used solely for metabolic calculations (BMR/TDEE).</li>
                                        <li>Dietary preferences and restrictions.</li>
                                        <li>Email address (for authentication and account recovery).</li>
                                    </ul>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">2. Data Usage</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        We use your data strictly to:
                                    </p>
                                    <ul className="list-disc pl-5 text-slate-600 space-y-1">
                                        <li>Generate your personalized meal plans via AI.</li>
                                        <li>Authenticate your access to the platform.</li>
                                        <li>Process payments (via third-party provider Dodo Payments).</li>
                                    </ul>
                                    <p className="text-slate-600 mt-2 font-bold">We DO NOT sell your personal data to third parties.</p>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">3. Data Security</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        We implement standard security measures including encryption in transit (HTTPS) and at rest (Database encryption). Authentication is handled via secure OTP (One Time Password) to prevent password theft.
                                    </p>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">4. Your Rights</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        You have the right to request deletion of your data at any time by contacting support.
                                    </p>
                                </section>
                            </div>
                        )}

                        {/* REFUND POLICY */}
                        {activeSection === 'refund' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                                <h1 className="text-3xl font-black text-dark">Refund Policy</h1>

                                <div className="p-6 bg-slate-50 rounded-2xl border border-slate-100">
                                    <h3 className="text-xl font-bold text-dark mb-4">Digital Goods Policy</h3>
                                    <p className="text-slate-600 leading-relaxed mb-4">
                                        Since DietlyPlans provides non-tangible, irrevocable digital goods (instant generation of AI Meal Plans and PDF downloads), <strong className="text-dark">we generally do not issue refunds once the order is accomplished and the product is unlocked.</strong>
                                    </p>
                                    <p className="text-slate-600 leading-relaxed">
                                        As a customer, you are responsible for understanding this upon purchasing any item at our site.
                                    </p>
                                </div>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">Exceptions</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        We realize that exceptional circumstances can take place with regard to the character of the product we supply. Therefore, we DO honor requests for refunds for the following reasons:
                                    </p>
                                    <ul className="list-disc pl-5 text-slate-600 space-y-2">
                                        <li><strong>Non-delivery of the product:</strong> Due to some mailing issues of your e-mail provider or your own mail server, you might not receive a delivery e-mail from us. In this case, we recommend contacting us for assistance.</li>
                                        <li><strong>Major defects:</strong> Although all the products are thoroughly tested before release, unexpected errors may occur. If we cannot resolve a substantial issue within a reasonable timeframe, a refund may be issued.</li>
                                        <li><strong>Accidental Duplicate Purchase:</strong> If you accidentally purchased the same plan twice.</li>
                                    </ul>
                                </section>

                                <section className="space-y-2">
                                    <h3 className="text-xl font-bold text-dark">Contact Support</h3>
                                    <p className="text-slate-600 leading-relaxed">
                                        Requests for refunds must be made within 7 days of the original purchase. Please contact our support team with your transaction ID.
                                    </p>
                                </section>
                            </div>
                        )}

                    </div>
                </div>
            </div>
        </div>
    );
};
