-- Enable RLS
alter table auth.users enable row level security;

-- 1. PLANS TABLE (Active User State)
create table if not exists public.plans (
  user_id uuid references auth.users(id) on delete cascade primary key,
  data jsonb not null,
  is_paid boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.plans enable row level security;

create policy "Users can view their own plan" 
  on public.plans for select 
  using (auth.uid() = user_id);

create policy "Users can update their own plan" 
  on public.plans for update 
  using (auth.uid() = user_id);

create policy "Users can insert their own plan" 
  on public.plans for insert 
  with check (auth.uid() = user_id);
  
-- Allow Service Role (Edge Functions/Webhooks) to bypass RLS full access
-- Note: Service Role bypasses RLS by default, but good to be explicit if needed in future.

-- 2. ACTIVITY LOGS (Tracking)
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  action_type text not null,
  metadata jsonb,
  created_at timestamptz default now()
);

alter table public.activity_logs enable row level security;

create policy "Users can insert logs" 
  on public.activity_logs for insert 
  with check (auth.uid() = user_id);
  
-- No select policy for users (Logs are for admin/internal use)

-- 3. PLAN HISTORY (Archives)
create table if not exists public.plan_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  full_data jsonb not null,
  created_at timestamptz default now()
);

alter table public.plan_history enable row level security;

create policy "Users can insert history" 
  on public.plan_history for insert 
  with check (auth.uid() = user_id);

create policy "Users can view own history" 
  on public.plan_history for select 
  using (auth.uid() = user_id);
